x-service-node-webapp-development-base: &node-webapp-development-base
  build:
    args:
      GID: ${GID:-0}
      UID: ${UID:-0}
    context: Dockerfile.d/node-webapp.development
  command:
    - zsh
    - --login
    - -c
    - |
      npm-check-updates --upgrade
      npm install
      npm audit fix
      sort-package-json
      sleep infinity
  init: true
  user: ${UID:-0}:${GID:-0}
  volumes:
    - home-developer:/home/developer
    - home-root:/root # for macOS & Windows
    - .:/workspace
  working_dir: /workspace

services:
  workspace:
    <<: *node-webapp-development-base

version: "3.9"
volumes:
  home-developer:
    driver: local
  home-root:
    driver: local
