version: "3.7"
services:
  dev:
    build:
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
      context: Dockerfile.d/dev
    command:
      - bash
      - -c
      - |
        npm-check-updates --upgrade
        npm install
        npm audit fix
        sort-package-json
        npm run test:coverage -- --watch
    environment:
      - PORT=4000
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:4000:4000"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - provisioning-root:/root # for macOS
      - provisioning-home-developer:/home/developer
      - provisioning-home-node:/home/node
      - ~/.ssh:/root/.ssh:ro # for macOS
      - ~/.ssh:/home/developer/.ssh:ro
      - ~/.ssh:/home/node/.ssh:ro
      - .:/workspace
    working_dir: /workspace
volumes:
  provisioning-root:
    driver: local
  provisioning-home-developer:
    driver: local
  provisioning-home-node:
    driver: local
