version: "3.7"
services:
  dev:
    build:
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
      context: Dockerfile.d/dev
    command:
      - bash
      - -c
      - |
        npm install
        npm run test:coverage -- --watch
    environment:
      - PORT=4000
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:4000:4000"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - provisioning-home:/root # for macOS
      - provisioning-home:/home/developer
      - provisioning-home:/home/node
      - ~/.ssh:/root/.ssh:ro # for macOS
      - ~/.ssh:/home/developer/.ssh:ro
      - ~/.ssh:/home/node/.ssh:ro
      - .:/workspace
    working_dir: /workspace
volumes:
  provisioning-home:
    driver: local
