version: "3.7"
services:
  dev:
    build:
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
      context: Dockerfile.d/dev
    command:
      - bash
      - -c
      - |
        npm install
        npm run test:coverage -- --watch
    environment:
      - PORT=4000
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:4000:4000"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - .:/workspace
    working_dir: /workspace
