version: "3.7"

services:
  app:
    build:
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
      context: Dockerfile.d/app.development
    command:
      - bash
      - -c
      - |
        npm-check-updates --upgrade
        npm install
        npm audit fix
        sort-package-json
        npm run dev
    environment:
      - PORT=4000
    ports:
      - "${BIND_IP_ADDR:-127.0.0.1}:4000:4000"
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - .:/workspace
      - ./config/app:/data/config/app:ro
    working_dir: /workspace
  provisioning:
    build:
      context: Dockerfile.d/provisioning
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
    command:
      - bash
      - -c
      - |
        gcloud auth activate-service-account --key-file=/workspace/config/credentials/google-cloud-keyfile.json
        gcloud auth configure-docker gcr.io --quiet
        gsutil ls gs://${PROJECT_UNIQUE_ID}-provisioning/ > /dev/null 2>&1\
        || gsutil mb gs://${PROJECT_UNIQUE_ID}-provisioning/
        gsutil acl set private gs://${PROJECT_UNIQUE_ID}-provisioning/
        gsutil versioning set on gs://${PROJECT_UNIQUE_ID}-provisioning/
        sudo chown $$(id -u) /var/run/docker.sock
        sudo chmod a+rwx /tmp/provisioning
        terraform init -backend-config="bucket=${PROJECT_UNIQUE_ID}-provisioning"
    environment:
      - TF_DATA_DIR=/tmp/provisioning
      - GOOGLE_CLOUD_KEYFILE_JSON=/workspace/config/credentials/google-cloud-keyfile.json
      - GOOGLE_APPLICATION_CREDENTIALS=/workspace/config/credentials/google-cloud-keyfile.json
      - CLOUDSDK_CORE_PROJECT
      - PROJECT_UNIQUE_ID
      - TF_VAR_basename
      - TF_VAR_gcp_default_region
      - TF_VAR_gcp_project_id
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - provisioning-tmp:/tmp/provisioning
      - provisioning-home-root:/root # for macOS
      - provisioning-home-developer:/home/developer
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    working_dir: /workspace
volumes:
  provisioning-tmp:
    driver: local
  provisioning-home-root:
    driver: local
  provisioning-home-developer:
    driver: local
