name: publish-npm-package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: npm install --global can-npm-publish
      - run: npm install
      - run: npm test
      - name: publish to npm
        run: can-npm-publish --verbose && npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: "registry=https://npm.pkg.github.com"
          scope: "@mazgi"
      - run: |
          cat package.json | jq '.name="@mazgi/express-middleware-redirector"' > package.gpr.json
          mv package.gpr.json package.json
      - run: |
          cat package.json | jq '.publishConfig.registry="https://npm.pkg.github.com/"' > package.gpr.json
          mv package.gpr.json package.json
      - name: publish to github
        run: can-npm-publish --verbose && npm publish --access public || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
